SYN-1771 sdk에 filesystem과 s3 스토리지 연동
datamaker-kr/datamaker-sdk pull request #17
Opened 2024-09-11 07:58 UTC by haremeat

### 개요
- filesystem과 s3 연동 코드를 추가하고 기본적으로 sdk에서 스토리지별로 pathlib을 가져와서 임포트할 수 있도록 만들었습니다.
- 관련 지라 : https://datamaker.atlassian.net/browse/SYN-1771

### 설명
- 기존 일반 FileSystem으로만 작동하던 get_storage를 수정하여 스토리지에 맞는 Class를 리턴하도록 만들었습니다.
- 이로 인해 플러그인은 어떤 스토리지를 사용하는지 알 필요 없이 get_pathlib()만 사용하여 임포트할 수 있습니다.
- Provider에는 가장 기본적인 get_pathlib만 정의하였습니다.

### 개발 요구사항
- 에이전트를 통해 임포트를 할 수 있다.
- 플러그인에서 바로 pathlib을 사용하여 임포트하기

### 기타
- 연동은 일단 s3와 filesystem만 넣었습니다.
- 따로 외부 클라이언트용 플러그인을 만들 필요는 없기때문에 [datamaker-file-and-folder-import-plugin](https://github.com/datamaker-kr/datamaker-file-and-folder-import-plugin)을 그대로 사용하려합니다.

2024-09-11 08:42 UTC, haremeat commented
@enoch2110 리뷰 부탁드립니다~!

2024-09-19 16:24 UTC, enoch2110 requested changes

2024-09-19 16:24 UTC, enoch2110 commented on datamaker/core/storage_providers/__init__.py
> +        raise NotImplementedError
[P3]
ABC를 사용하셨는데 여기에 abstractmethod decorator를 사용하지 않은 이유가 있나요?

2024-09-19 16:24 UTC, enoch2110 commented on datamaker/core/storage_providers/__init__.py
> +class BaseProvider(metaclass=ABCMeta):
[P4]
https://docs.python.org/3/whatsnew/3.4.html#abc

ABC 클래스 inherit을 하는 것이 더 깔끔할 듯 합니다.

2024-09-19 16:24 UTC, enoch2110 commented on datamaker/core/storage_providers/amazon_s3.py
> +            boto3.setup_default_session(**boto3_configs)
[P1]
boto3 자체에 global하게 default session을 걸어주면 여러 s3 client를 활용할 때 문제가 발생할 것 같습니다.

boto3.client (직접 사용해보진 않아서 확실하진 않음) 함수와 같이 client instance를 생성해서 처리해야 합니다.

client기반으로 하면 s3_init 변수도 필요없을 듯 해지고 attribute로 client = None 하시고 client가 없을 때만 생성하는 식으로 하면 될 것 같습니다.

2024-09-19 16:24 UTC, enoch2110 commented on datamaker/core/storage_providers/amazon_s3.py
> +        return pathlib_object
[P4]
은정님 단골 스타일이긴 한데 불필요한 변수는 필요 없을 것 같습니다.

그리고 _get_s3_path를 별도로 구현할 필요 없이 그냥 get_pathlib에 구현해도 무방할 듯 합니다.

```suggestion
        return self._get_s3_path()
```

2024-09-19 16:24 UTC, enoch2110 commented on datamaker/core/storage_providers/__init__.py
> +class BaseProvider(metaclass=ABCMeta):
[P3]
```suggestion
class BaseStorageProvider(metaclass=ABCMeta):
```

2024-09-23 07:43 UTC, haremeat commented
@enoch2110 리뷰 적용하였습니다!

2024-09-23 08:08 UTC, enoch2110 requested changes

2024-09-23 08:08 UTC, enoch2110 commented on datamaker/core/storage_providers/__init__.py
> +        raise NotImplementedError
[P3]
`@abstractmethod`를 쓴 이상 `raise NotImplementedError`는 불필요한 코드입니다.
```suggestion
        pass
```

2024-09-23 08:08 UTC, enoch2110 commented on datamaker/core/storage_providers/amazon_s3.py
> +        return s3path.S3Path(f'/{bucket_name}')
[P1]
아직 글로벌하게 처리되고 있는 것 같습니다.

아래 코드가 의도대로 처리될 수 있어야 합니다.

```python
storage_1 = AmazonS3StorageProvider({...})
storage_2 = AmazonS3StorageProvider({...})


storage_1.get_pathlib()
storage_2.get_pathlib()
storage_1.get_pathlib()
```

2024-09-23 09:30 UTC, haremeat commented on datamaker/core/storage_providers/amazon_s3.py
> +        return s3path.S3Path(f'/{bucket_name}')
register_configuration_parameter가 path로 넘긴 특정 경로(위 코드상으로는 PureS3Path(f'/{bucket_name}')) 에만 s3_resource를 설정할 수 있는 함수였습니다.
때문에 글로벌하게 처리되지 않는 것을 확인하였습니다.

대표님이 테스트하라고 하신대로 테스트했을 때 영향을 주지 않고 의도대로 처리되는 걸 확인하였습니다.

2024-09-24 00:17 UTC, haremeat commented on datamaker/core/storage_providers/amazon_s3.py
> +        return s3path.S3Path(f'/{bucket_name}')
그런데 대표님... 원래 코드였던 `setup_default_session`도 같은 방식으로 테스트했을 때 서로 영향이 없는 것 같습니다!

2024-09-24 08:08 UTC, enoch2110 commented on datamaker/core/storage_providers/__init__.py
> +        raise NotImplementedError
이거 해결이 안되셨습니다

2024-09-24 08:11 UTC, haremeat commented on datamaker/core/storage_providers/__init__.py
> +        raise NotImplementedError
아 아래  부분까지 체크되면 push하려고 했던 부분이긴한데 지금 Push하겠습니다!!

2024-09-24 08:13 UTC, haremeat commented
@enoch2110 리뷰 적용되었습니다!

2024-09-24 08:27 UTC, enoch2110 approved these changes

2024-09-25 04:14 UTC, merged