DATAMAKER-18 : 익스포터 기본 기능
datamaker-kr/datamaker-sdk pull request #2
Opened 2023-07-13 10:36 UTC by haremeat

- 원본 파일명을 가져오기 위한 `get_data_unit`
- 할당작업의 data를 가져오기 위한 `get_assignment`
- 할당작업이 여러 개일 경우 선택을 위한 `list_assignments`

총 세 가지 기능을 추가하였습니다.

2023-07-14 13:55 UTC, enoch2110 requested changes
export시 detail api로 정보를 가져오는 것인 지양해야 할 것 같습니다. list api에서 원하는 정보를 받아올 수 있는 방향으로 진행해야 할 듯 합니다.

원본파일명을 가져오는 것도 get_data_unit을 통하는 것이 아닌 list_assignments, list_labels를 통해 접근 가능하도록 백엔드에서 수정이 될 예정입니다.

2023-07-14 13:55 UTC, enoch2110 commented on datamaker/client/mixins/dataset.py
> +        path = f'data_units/{pk}/'
"/" 끝에 붙여야 한다고 코멘트 달아야지 생각했었는데 어느새 달려있네요 ㅋㅋㅋ 굿잡입니다.

2023-07-14 13:55 UTC, enoch2110 commented on datamaker/client/__init__.py
> +             HumanInTheLoopClientMixin,
HumanInTheLoopClientMixin -> HITLClientMixin으로 합시다

2023-07-15 02:14 UTC, haremeat commented
리뷰 주신 부분 수정하였습니다! 

다만 detail api로 정보를 가져오는 것인 지양해야 할 것 같다고 하셨던 부분에 대해 질문드리고 싶은 게 있습니다.
현재는 agent에서 `get_assignment`를 통해서 필요한 json data를 가져오고 있는데 혹시 이 부분도 `list_assignments`를 통해 가져오는 방식으로 변경될 예정인걸까요?
일단은 get_assignment는 삭제하지 않았습니다.

2023-07-15 08:20 UTC, enoch2110 commented
- assignments list api를 통해 data를 가져와야 할 것을 말씀 드린 것이 맞습니다.
- 해당 api를 누가 어떻게 개발할 것인지는 같이 논의해보면 좋을 듯 합니다.
- 특정 기능을 api를 통해 구현하고자 할때 제공되는 api에서 어떻게든 하는 방식보다는 api에서 최적화된 기능을 제공하지 않으면 api도 직접 구현/개선 한다는 옵션은 상시 염두하자는 취지 입니다!

2023-07-15 08:20 UTC, enoch2110 approved these changes

2023-07-17 00:23 UTC, merged