DATAMAKER-881 업로더로 부터 에이전트가 외부 스토리지의 정보와 경로를 받아서 임포트 할 수 있도록
datamaker-kr/datamaker-sdk pull request #4
Opened 2023-07-26 09:27 UTC by haremeat

- 데이터셋을 가져오는 get_dataset 
- 스토리지 정보를 가져오는 get_storage를 추가하였습니다.
- `prepare_dataset`을 플러그인에서 처리하는 형식이라 생각하고 코딩하였습니다.
- groups와 batch_size는 필수값이 아니라 생각해서 kwargs를 통해 받았습니다.
- 데이터는 대표님과 구두로 상의한대로 /mnt/projects/ 에 있다고 가정하고 코딩하였습니다.
- 최종적으로 나오는 dataset은 아래와 같습니다.

````
[
  {'files': {'data': PosixPath('/mnt/exports/agent_export_test/199-new55/37669.json'), 'image': PosixPath('/mnt/exports/agent_export_test/199-new55/37669.jpg')
    }, 'groups': ['08_oid-train'
    ]
  },
  {'files': {'data': PosixPath('/mnt/exports/agent_export_test/199-new55/37669_1.json'), 'image': PosixPath('/mnt/exports/agent_export_test/199-new55/37669_1.jpg')
    }, 'groups': ['08_oid-train'
    ]
  },
  {'files': {'data': PosixPath('/mnt/exports/agent_export_test/199-new55/37669_2.json'), 'image': PosixPath('/mnt/exports/agent_export_test/199-new55/37669_2.jpg')
    }, 'groups': ['08_oid-train'
    ]
  }
]
````

2023-08-03 06:07 UTC, enoch2110 requested changes
Base처리할 로직이 아닌 것이 많이 포함되어있습니다.

2023-08-07 05:51 UTC, haremeat commented
- 구두로 말씀하신대로 get_files, prepare_dataset은 플러그인에서 따로 처리하는 방식으로 변경하였습니다.
- init이 아닌 import_dataset에서 필요한 데이터를 받는 형식으로 변경하였습니다!

2023-08-16 16:47 UTC, enoch2110 requested changes
ImportsService의 변경된 내용에 따라 수정필요

2023-08-16 16:47 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +    def get_files(self, storage, paths, allowed_extensions, configuration):
`get_files`의 존재의 이유를 잘 모르겠습니다. `prepare_dataset`만으로는 충분하지 않은걸까요?

2023-08-16 16:47 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        return response
response를 별도로 return하는 이유가 있을까요?

만약 오류가 발생했는데 현재와 같이 처리된다면 task는 성공으로 처리 되고 세부 내용을 통해 오류를 보게 되어 그냥 오류는 raise하는게 나을 듯 합니다.

2023-08-21 08:18 UTC, haremeat commented
- ImportsService에서 변경된 로직에 따라 수정하였습니다!

2023-08-22 07:18 UTC, enoch2110 requested changes

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        super().__init__(**kwargs)
아래 코드 추가하고 이후 client 접근은 `self.logger.client`가 아니라 `self.client`로 접근. logger에 client가 없을 수 있기 때문에 해당 Plugin은 logger에 client가 꼭 있어야 함을 명시하기 위함.
```python
self.client = self.logger.client
assert bool(self.client)
```

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        batch_size,
kwarg로 변경

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +            allowed_extensions[new_key] = extensions
dataset의 allowed_extensions 바로 사용

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        storage,
storage -> storage_id

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +            dataset = self.logger.client.get_dataset(self.target_id)
```python
if self.category == 'project':
    project_id = self.target_id
    dataset_id = self.client.get_project(project_id)['dataset']
else:
    project_id = None
    dataset_id = self.target_id
    
dataset = self.client.get_dataset(dataset_id)
```

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        configuration = self.configuration
제거

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +
`self.storage_id`로 storage가져오기

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +            raise e
```python
self.client.import_dataset(
    dataset_id,
    dataset,
    project_id=project_id,
    batch_size=self.batch_size
)
```

그리고 exception처리시 e를 바로 raise하는 경우 별도의 try, except문은 불필요함.

2023-08-22 07:18 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +            self.storage, self.paths, allowed_extensions, configuration
self.storage -> storage

2023-08-23 07:25 UTC, haremeat commented
리뷰 주신대로 수정하였습니다!
- get_storage에서 payload 받는 방식으로 변경하였습니다.

2023-08-23 08:06 UTC, enoch2110 requested changes

2023-08-23 08:06 UTC, enoch2110 commented on datamaker/client/mixins/integration.py
> +    def get_storage(self, pk, data):
get은 data가 아니라 params가 좀더 적당할 듯 합니다. 그리고 arg가 아니라 kwarg로 부탁드립니다.

2023-08-23 08:06 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        self.logger.client.import_dataset(
`self.logger.client` -> `self.client`

2023-08-23 08:06 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        self.batch_size = kwargs.pop('batch_size')
batch_size는 존재하는 것을 가정한 상태이기 때문에 kwarg를 pop하지 않고 init에 명시

2023-08-23 08:40 UTC, haremeat commented
수정하였습니다! 다만 batch_size는 제가 제대로 알아듣고 처리한 건지 모르겠네요...

2023-08-24 07:06 UTC, enoch2110 requested changes

2023-08-24 07:06 UTC, enoch2110 commented on datamaker/client/mixins/integration.py
> +    def get_storage(self, pk, **params):
`**params` -> `params=None`

2023-08-24 07:06 UTC, enoch2110 commented on datamaker/plugins/imports.py
> +        batch_size,
`batch_size` -> `batch_size=500` batch_size default값은 적절히 수정하시면 됩니다.

2023-08-24 07:13 UTC, haremeat commented on datamaker/plugins/imports.py
> +        batch_size,
수정하였습니다! 다만 ImportsServiceSerializer에서 이미 batch_size = serializers.IntegerField(default=500)를 주고 있는데 여기서 또 default값을 줘야 하는 이유가 뭔지 혹시 알 수 있을까요?

2023-08-24 07:42 UTC, enoch2110 approved these changes

2023-08-24 07:43 UTC, merged